### ISSUE TITLE
Leadás előtti észrevételeim a cikkel kapcsolatban

### ISSUE THREAD

**Issue by balogandras** [lilasaba/medilatin#11]
Előre is bocsánat a szőrszálhasogatásért, ne haragudj, mindent vegyél építő szándékkal:

"In one hand" : szerintem "on"

"it is also has to be taken into account" : "is" nem kell

"Both dev and test sets were read out loud" : én nem tudok dev és test halmazról

"2.2 Speech data Training data": itt meg kellene említeni, hogy AM tanító anyagról van szó

"Native speakers of Czech, Hungarian, Polish and Slovakian": of után jók ezek a melléknevek? Utána n-dash kellene, nem kötőjel. A " - " karaktersorozatokban a kötőjeleket javítani kellene n-dashre.

"One obvious way to handle this problem is create": to create

"Another way of circumvent" : to circumvent vagy of circumventing (szerintem)

"Gauss Mixture Model": Gaussian

"KALDI": Kaldi

"As source language acoustic training data, Czech and Hungarian phoneme-based acous- tic models were used": Ezt nem értem. Mit akar jelenteni ez, hogy akusztikus modelleket tanító adatként használunk?

"source languages phonemes": language ? vagy ha többes számban akarod, akkor languages'

"Table 1": Ezt nem értem. A táblázat jobb alsó negyedében fonémák vannak vagy grafémák? Ha grafémák, akkor nem jó az áthúzott o, olyan betű nincs a magyarban. Ha fonémák, akkor miért különböző a cseh és latinnál? (Bocs, ha butaság, te értesz ehhez.) Nekem nem illik a többihez, hogy középre van igazítva a "Table 1 ..."

"Table 2": A palatal vowel miért VP, miért nem PV? "VNP": mi az az N?

Nézem tovább, küldöm a másik felét is, ha végigértem, de hátha addig foglalkoznál ezzel, azért küldöm most el.

**Comment by balogandras** [comment]
Ja, és simán lehet, hogy nincs igazam, én érzem rosszul a nyelvet, vagy kevésbé értek a témához, mint te, csak meggondolásra bocsátom az észrevételeimet.

**Comment by lilasaba** [comment]
Ezek tokjok, koszi, a VNP non-palatal vowel akart lenni, csak elfelejtettem feloldani, de inkabb megvaltoztattam vegul.

Az athuzott o az IPA ö fonema, ez csak magyarban van, csehben tudtommal nincs, azert kulonbozo a ket szabaly.

**Comment by balogandras** [comment]
A konkrét kísérletek eredményeiben, az összehasonlítások tanulságaiban nem vagyok benne igazán (ezzel kapcsolatban Péter írt), a továbbiakban is nyelvtani, szerkesztési és AM elméleti kötözködések következnek:

"Our motivation with using" : motivation of

"Further than that": ilyet még nem hallottam/olvastam. Esetleg furthermore?

"due to the fact, that": nem kell vessző

"see Section 2.1": elé kellene vessző

"with 34.4% overall WER (see in Table 3)": nincs ilyen szám a táblázatban

"Table 3": hogy világosabb legyen, odaírhatod, hogy _acoustic_ models

Tudom, hogy automatikusan tex-el generált táblázatok, de ha nem nagyon bonyolult, beállíthatnád, hogy szellősebb legyen, mert szinte összeérnek a számok

"Acoustic model size: 76 hours.": Tudom, mit jelent, és hogy azért így írtad, hogy rövid legyen, de ez így akkor is pontatlan. (Egy AM méretének ilyeneket lehet tekinteni, mint rétegszám, senon szám, rétegenkénti neuron szám, stb.) Röviden lehete szerintem: Acoustic mode training set: 76 hours. Table 5-ben ugyanígy.

"The most striking results are the Czech speakers": ez így nem jól van fogalmazva. Nem a cseh beszélők az eredmények, hanem a cseh beszélők adják az eredményeket.

"eliminate the efforts": lehet, hogy nincs igazam, de nekem az "eliminate" olyasmit jelent, hogy valami kellemetlen dolgot, _ami_már_létezik_, megsemmisítünk, kiküszöbölünk, de most azt akarjuk, hogy egy lehetséges dolgot, ami még nincs is, ne is legyen. Talán avoid? De lehet, hogy jó így is.

"ultimately Romanian": szerintem inkább lastly

"by large": by far?

Reference: Nagy kezdőbetűkkel a cikkek címeit, de legalább az egyébként is nagybetűs szavakat, pl: Kaldi, European, Speecon

**Comment by mihajlik** [comment]
A "Further than that" szerintem teljesen OK, a többivel egyetértek, köszi András. Meg neked is Lili, ha jövő héten még szóba állsz velünk :)

**Comment by mihajlik** [comment]
Bocs, a saját esti szövegeimben hiba: 
- az elején a perplexitásoknál "text" helyet "texts".
- a konklúzió utolsó mondatában "in" után egy "an" talán jobb (mintha nem lenne ott)

**Comment by lilasaba** [comment]
Vege, feltoltottem a legfrissebb verziot a tsd honlapra, koszi nagyon az eszreveteleket.
