### ISSUE TITLE
Grafema-normalizalasi statisztika az USG modellhez

### ISSUE THREAD

**Issue by lilasaba** [lilasaba/medilatin#15]
@balogandras, a legutobbi megbeszelesen abban maradtunk, hogy mivel tobb biralo is hianyolta a peldakat a diakritikumos grafemakrol a legkozelebbi normal alakra valo mappelesrol, hogy nem csak peldakkal fogjuk egy kicsit feldusitani a cikkeket, hanem ossze is szamoljuk, hany ilyen atalakitas tortent.  
Ezt en megcsinalom, viszont ha lesz majd valamikor ot perced, akkor at tudnad majd kuldeni a mappeleseket tartalmazo fajlokat ?

Koszi !

**Comment by balogandras** [comment]
erre gondolsz?

s:Á:A:g                                                                                                                                                                                                                                       
s:É:E:g                                                                                                                                                                                                                                       
s:Í:I:g                                                                                                                                                                                                                                       
s:Î:I:g                                                                                                                                                                                                                                       
s:Ó:O:g                                                                                                                                                                                                                                       
s:Ö:O:g                                                                                                                                                                                                                                       
s:Ú:U:g                                                                                                                                                                                                                                       
s:Ü:U:g                                                                                                                                                                                                                                       
s:Ý:Y:g                                                                                                                                                                                                                                       
s:á:a:g                                                                                                                                                                                                                                       
s:â:a:g                                                                                                                                                                                                                                       
s:é:e:g                                                                                                                                                                                                                                       
s:í:i:g                                                                                                                                                                                                                                       
s:î:i:g                                                                                                                                                                                                                                       
s:ó:o:g                                                                                                                                                                                                                                       
s:ö:o:g                                                                                                                                                                                                                                       
s:ú:u:g                                                                                                                                                                                                                                       
s:ü:u:g                                                                                                                                                                                                                                       
s:ý:y:g                                                                                                                                                                                                                                       
s:ă:a:g                                                                                                                                                                                                                                       
s:ą:a:g                                                                                                                                                                                                                                       
s:ć:c:g                                                                                                                                                                                                                                       
s:Č:C:g                                                                                                                                                                                                                                       
s:č:c:g                                                                                                                                                                                                                                       
s:ď:d:g                                                                                                                                                                                                                                       
s:Ę:E:g                                                                                                                                                                                                                                       
s:ę:e:g                                                                                                                                                                                                                                       
s:ě:e:g                                                                                                                                                                                                                                       
s:Ł:L:g                                                                                                                                                                                                                                       
s:ł:l:g                                                                                                                                                                                                                                       
s:ń:n:g                                                                                                                                                                                                                                       
s:ň:n:g                                                                                                                                                                                                                                       
s:Ő:O:g                                                                                                                                                                                                                                       
s:ő:o:g                                                                                                                                                                                                                                       
s:ř:r:g                                                                                                                                                                                                                                       
s:Ś:S:g                                                                                                                                                                                                                                       
s:ś:s:g                                                                                                                                                                                                                                       
s:Ş:S:g                                                                                                                                                                                                                                       
s:ş:s:g                                                                                                                                                                                                                                       
s:š:s:g                                                                                                                                                                                                                                       
s:Ţ:T:g                                                                                                                                                                                                                                       
s:ţ:t:g                                                                                                                                                                                                                                       
s:ť:t:g                                                                                                                                                                                                                                       
s:ů:u:g                                                                                                                                                                                                                                       
s:Ű:U:g                                                                                                                                                                                                                                       
s:ű:u:g                                                                                                                                                                                                                                       
s:ź:z:g                                                                                                                                                                                                                                       
s:Ż:z:g                                                                                                                                                                                                                                       
s:ż:z:g                                                                                                                                                                                                                                       
s:Ž:z:g                                                                                                                                                                                                                                       
s:ž:z:g

**Comment by lilasaba** [comment]
Igen, köszi ! A kis-nagybetű különbségeket gondolom összevonhatom.

**Comment by balogandras** [comment]
A statisztika számításhoz úgy ésszerű szerintem is.

**Comment by lilasaba** [comment]
Idemásolom az összes grafémát (4-nyelvű USG):

    a
    b
    c
    d
    e
    f
    g
    h
    i
    j
    k
    l
    m
    n
    o
    p
    q
    r
    s
    t
    u
    v
    w
    x
    y
    z
    á
    â
    é
    í
    î
    ó
    ö
    ú
    ü
    ý
    ă
    ą
    ć
    č
    ď
    ę
    ě
    ł
    ń
    ň
    ő
    ř
    ś
    ş
    š
    ţ
    ť
    ů
    ű
    ź
    ż
    ž

**Comment by lilasaba** [comment]
Statisztikak bekerultek a cikkbe.
