### ISSUE TITLE
tsd cikk lektoralas

### ISSUE THREAD

**Issue by lilasaba** [lilasaba/medilatin#4]
Szia Peter,

feltoltottem a cikk lektoralando verziojat. A pull request-elos megoldas szerintem remekul mukodik.

Erdemi valtozasok az utolso kommunikacio ota:

+ SK eredmenyek explicitte tetele

TODOk (amik mar nem zavarjak a lektoralast, kerlek jelezd, ha be tudsz valamelyiknel segiteni):

+ related work: szerintem a Tanja Schultz-os, es az under-resource survey-s cikkrol kellene meg emlitest tenni
+ Roman speech database emlitese referenciaval (a referenciara mindenkepp szuksegem lenne)
+ boldface best results in tables (Lili - ezt meg ma megcsinalom, csak kicsit pepecselosebb annal, hogy erre kelljen varni)

**Comment by lilasaba** [comment]
Ja, es kerlek szolj, ha van mar dontes a mai submit-telessel kapcsolatban.

**Comment by mihajlik** [comment]
Mindjárt írok pár észrevételt változtatási javaslatot a szokásos módon.

A feltöltést valahol már írtam, hogy lehet, de teljesn jó lesz holnap is.

**Comment by lilasaba** [comment]
Ok, koszi.

Csinaltam meg par apro valtoztatast a fent leirt todo-kal kapcsolatban - ezt a valtozatot akkor most proba submit-telem. Az 'author' mezot egyelore uresen hagyom. Remelem ez igy ok, es akkor hnap folyt.

**Comment by mihajlik** [comment]
Az Interspeech-es cikkből át lehet venni a román referenciát (Broadcast News Transcription for Central-East Eu...)

**Comment by lilasaba** [comment]
Vegleges verzio feltoltve.
