### ISSUE TITLE
Replace Table 6 with 4*3-lang USG + 4-lang USG

### ISSUE THREAD

**Issue by lilasaba** [lilasaba/medilatin#8]
+ add 112h broadcast news info for hu

**Comment by mihajlik** [comment]
Lili, a számokra figyelj majd a táblákban. A jelenlegi 7.-ben a PL-HU 10.0 biztos nem jó, én legalábbis 9.09-et látok András kiértékelésében.

**Comment by lilasaba** [comment]
Ha a 4-nyelvu usg (hu:  112h) pl-speaker, hu-paragrafus eredmenyre gondolsz, akkor az nekem stimmelni latszik:

https://github.com/lilasaba/medilatin/blob/master/results/CZ_HU_PL_RO_USG_paragraph.log#L13

**Comment by mihajlik** [comment]
Andras home-jaban 9.09-et láttam ugyanitt. Most nem tudom ellenőrizni, de
biztos hogy volt ilyen szam valahol meg a nagy 4es usg előtt.
P

2017. ápr. 7. 9:26 ezt írta ("lilasaba" <notifications@github.com>):

**Comment by lilasaba** [comment]
Lehet, h teljesen megorultem, de most ellenoriztem kozvetlenul Andras home-jaban, es szerintem a hu-567-oras `cz_hu_pl_ro_usg` **rosszabb**, mint a hu-112-oras `cz_hu_pl_ro_usg`.

**Comment by lilasaba** [comment]
@mihajlik, ugy nez ki a `hu-112-oras cz_hu_pl_ro_usg` **26.03**, a `hu-567-oras cz_hu_pl_ro_usg` pedig **28.03**.

Az eredmenyek aranyosan valtoznak, ha kivesszuk az LT beszelot.

Az a kerdes tehat, h milyen iranyba menjunk vissza fele a regi verziohoz ?
